### ISSUE TITLE
update-manager crashed

### ISSUE THREAD

**Issue by talent-less** [ehfd/docker-nvidia-glx-desktop#10]
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 361, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.freedesktop.UpdateManager': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/UpdateManager/UpdateManager.py", line 458, in _setup_dbus
    proxy_obj = bus.get_object('org.freedesktop.UpdateManager',
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 277, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UpdateManager was not provided by any .service files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/update-manager", line 117, in <module>
    app = UpdateManager(data_dir, options)
  File "/usr/lib/python3/dist-packages/UpdateManager/UpdateManager.py", line 109, in __init__
    self._setup_dbus()
  File "/usr/lib/python3/dist-packages/UpdateManager/UpdateManager.py", line 469, in _setup_dbus
    self.dbusController = UpdateManagerDbusController(self, bus_name)
  File "/usr/lib/python3/dist-packages/UpdateManager/UpdateManager.py", line 478, in __init__
    self.alert_watcher = AlertWatcher()
  File "/usr/lib/python3/dist-packages/UpdateManager/Core/AlertWatcher.py", line 49, in __init__
    self.bus = dbus.Bus(dbus.Bus.TYPE_SYSTEM)
  File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 102, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 124, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory

```

**Comment by talent-less** [comment]
Solved by adding `/etc/init.d/dbus start` in to the start-up script.

**Comment by ehfd** [comment]
Will add DBus compatibility to next version.

**Comment by ehfd** [comment]
Will be fixed in next commit.
